### ISSUE TITLE
Transfer ownership to nrf-rs organization

### ISSUE THREAD

**Issue by jamesmunns** [themadinventor/nrf91-rs#3]
Hey @themadinventor, you mentioned in [this comment](https://github.com/themadinventor/nrf91-rs/pull/1#issuecomment-513546740) that you would be interested in transferring ownership of this repository.

We'd love to have this crate in the [nrf-rs](https://github.com/nrf-rs), and would be happy to continue maintenance.

To do this, you would need to:

* transfer the github repo
  * Go to Settings>Transfer repository
  * Follow the transfer confirmation steps
* grant crates.io publish rights
   * From the crate, follow the [cargo owner](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner) steps

For both of these, you can either transfer directly to the `nrf-rs` github organization, or you can transfer these to me, and I will get them included into the organization. Please feel free to reach out to me or anyone in the nrf-rs organization if you have any questions.

CC @thejpster (also a maintainer at [nrf-rs], and also works more directly with the nrf91)

**Comment by themadinventor** [comment]
Hi!
I'm more than happy to hand it over to you as I'm not actively working with Rust on the nRF91 anymore. I've sent a transfer request to you @jamesmunns , because it seems I can't transfer it to the organization directly.
I'll transfer the crate ownership as well, but I'm travelling and don't have the cargo environment set up on this laptop, so I'll get back to you asap.

Update: Sent crate ownership invite

**Comment by jamesmunns** [comment]
Thank you @themadinventor! I have now:

* Transferred the repository to the organization
* Created a new team, @nrf-rs/nrf91 
* I have given the above team publish rights to the crates.io repository.

If you are interested in picking up your work on this in the future, let us know! Thanks again for getting this started :)
